name: Python application (Windows Build)
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    env:
      APP_NAME: change-selection-color
      PYTHON_VERSION: "3.14"
      ICON_PATH: app/src/icon.ico
      RELEASE_NAME: "Release v0.0.0"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Build
        run: |
          pyinstaller app/main.py --onefile --name "${{ env.APP_NAME }}" --icon "${{ env.ICON_PATH }}" --collect-all pyaudiodevice
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.0.0
          release_name: ${{ env.RELEASE_NAME }}
          draft: true
          prerelease: false
      - name: Upload to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/${{ env.APP_NAME }}.exe
          asset_name: ${{ env.APP_NAME }}.exe
          asset_content_type: application/octet-stream
